### ISSUE TITLE
Hide VisualEditor warning "IE 11 browser not officially supported"

### ISSUE THREAD

**Issue by gabrielcossette** [gctools-outilsgc/gcpedia#34] opened 2017-02-10 14:27 UTC
Hi,

I don't use Internet Explorer myself but I've been told that when you use IE 11 to edit a page with the default VisualEditor mode, it shows a warning at the top right "You are using a browser which is not officially supported by this editor."

If IE 11 has shown to work well nonetheless, I propose that you hide this warning as this could affect user's confidence in the platform.

Thanks!

**Comment by pabrams** [comment] 2017-03-28 01:57
@gabrielcossette  I just tried reproducing, and I can confirm that when I edit my personal page I receive such a notification.  But are you saying that the notification is false?  If you're right, of course I agree that it should be removed, but if it's true that IE11 is not supported. the fix should be to support it fully, especially given that IE11 is the official government web browser, at least in my department, and apparently mediawiki is supposed to support IE9+ anyway:  http://www.mediawiki.org/wiki/Compatibility

**Comment by gabrielcossette** [comment] 2017-03-28 18:05
We need to look more specifically at the VisualEditor extension compatibility and it seems to support IE 11: https://www.mediawiki.org/wiki/VisualEditor/Target_browser_matrix So the notification message should not happen I guess.

But even if it wouldn't be officially supported by the upstream project, my assumption is that the GCTools decided to kind of support it when they deployed it. So the GC end user shouldn't ideally see this message.

**Comment by Phanoix** [comment] 2017-03-31 14:25
Look like when we upgrade that message should be gone then, if it's still going to be there for some reason I'll remove it manually.

**Comment by ToferC** [comment] 2017-06-30 18:45
I think this is gone. @Phanoix - please update or close if possible. Thanks!

**Comment by Phanoix** [comment] 2017-06-30 18:56
I don't think it's completely gone but it should be after it's upgraded to the latest version, so I'll close it for now since it should be solved as part the next full upgrade.

**Closed by Phanoix** 2017-06-30 18:56 UTC
Labels: usability
